version: "3.1"

services:
  app:
    image: ghcr.io/awaisch360/vibe:main
    container_name: api_service
    restart: always
    volumes:
      - ./shared_tmp:/armur/repos
    ports:
      - "4501:4500"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - APP_PORT=${APP_PORT}
    env_file:
      - .env
    depends_on:
      - redis_service

  redis_service:
    image: "redis:alpine"
    container_name: redis_service
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  worker:
    image: ghcr.io/awaisch360/vibe:main
    container_name: worker_service
    restart: always
    volumes:
      - ./shared_tmp:/armur/repos
    environment:
      - REDIS_ADDR=redis_service:6379
    env_file:
      - .env
    depends_on:
      - redis_service
    command: ["/usr/local/bin/armur-server"]
