version: "3.1"

services:
  app:
    image: ghcr.io/awaisch360/vibe:main
    container_name: api_service
    restart: always
    volumes:
      - ./shared_tmp:/armur/repos
    ports:
      - "4501:4500"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - APP_PORT=${APP_PORT}
      - DB_HOST=postgres_service
    env_file:
      - .env
    depends_on:
      - redis_service
      - postgres_service

  redis_service:
    image: "redis:alpine"
    container_name: redis_service
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

  worker:
    image: ghcr.io/awaisch360/vibe:main
    container_name: worker_service
    restart: always
    volumes:
      - ./shared_tmp:/armur/repos
    environment:
      - REDIS_ADDR=redis_service:6379
      - DB_HOST=postgres_service
    env_file:
      - .env
    depends_on:
      - redis_service
      - postgres_service
    command: ["/usr/local/bin/armur-server"]

  postgres_service:
    image: postgres:15-alpine
    container_name: postgres_service
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: armur
    ports:
      - "5432:5432"
